---
apiVersion: v1
kind: ConfigMap
metadata:
  name: xmodule-config
  namespace: xmodule
  {{- include "helm_lib_module_labels" (list . (dict "app" "xmodule")) | nindent 2 }}
data:
   {{ .Values.xmodule.settings | toYaml | nindent 4}}