---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: xmodule
  {{- include "helm_lib_module_labels" (list . (dict "app" "xmodule")) | nindent 2 }}
data:
  config: {{ .Values.xmodule.config | toYaml | nindent 4}}