{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: xmodule
  namespace: xmodule
  {{- include "helm_lib_module_labels" (list . (dict "app" "xmodule")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xmodule
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: xmodule
        minAllowed:
          cpu: 10m
          memory: 10Mi
        maxAllowed:
          cpu: 50m
          memory: 50Mi
{{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: xmodule
  namespace: xmodule
  {{- include "helm_lib_module_labels" (list . (dict "app" "xmodule")) | nindent 2 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: xmodule
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xmodule
  namespace: xmodule
  {{- include "helm_lib_module_labels" (list . (dict "app" "xmodule")) | nindent 2 }}
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.xmodule.replicas }}
  selector:
    matchLabels:
      app: xmodule
  template:
    metadata:
      labels:
        app: xmodule
    spec:
      priorityClassName: develop
      containers:
        - image: {{ include "helm_lib_module_image" (list . "service") }}
          imagePullPolicy: IfNotPresent
          name: service
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            requests:
              {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 14 }}
          {{- include "helm_lib_module_container_security_context_run_as_user_deckhouse_pss_restricted" . | nindent 10 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_deckhouse" . | nindent 6 }}