{{- if .Values.xmodule.registry }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: registrysecret
  namespace: xmodule
  {{- include "helm_lib_module_labels" (list . (dict "app" "xmodule")) | nindent 2 }}
data:
  .dockerconfigjson: {{ .Values.xmodule.registry.dockercfg }}
{{- end }}